-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-09-16 23:05:52 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
--  student name: Vladislav Pikulin
--  student id: 30935679

set echo on
spool mm_schema_output.txt



DROP TABLE assessment CASCADE CONSTRAINTS;

DROP TABLE centre CASCADE CONSTRAINTS;

DROP TABLE centre_class CASCADE CONSTRAINTS;

DROP TABLE centre_class_type CASCADE CONSTRAINTS;

DROP TABLE class_session CASCADE CONSTRAINTS;

DROP TABLE class_staffing CASCADE CONSTRAINTS;

DROP TABLE facility CASCADE CONSTRAINTS;

DROP TABLE member CASCADE CONSTRAINTS;

DROP TABLE payment CASCADE CONSTRAINTS;

DROP TABLE staff CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE assessment (
    assess_date         DATE NOT NULL,
    assess_bmi          NUMBER(3, 1),
    assess_weigh        NUMBER(4, 1),
    assess_blood_press  VARCHAR2(7),
    assess_vo2max       NUMBER(3, 1),
    staff_id            NUMBER(7) NOT NULL,
    member_no           NUMBER(7) NOT NULL
);

COMMENT ON COLUMN assessment.assess_date IS
    'the date on which this assessment was carried out';

COMMENT ON COLUMN assessment.assess_bmi IS
    'the bmi of the member who took this assessment';

COMMENT ON COLUMN assessment.assess_weigh IS
    'the weight of the member who took this assessment';

COMMENT ON COLUMN assessment.assess_blood_press IS
    'the blood pressure of the member who took this assessment';

COMMENT ON COLUMN assessment.assess_vo2max IS
    'the vo2max of the member who took this assessment';

COMMENT ON COLUMN assessment.staff_id IS
    'unique identifier for each staff member';

COMMENT ON COLUMN assessment.member_no IS
    'unique identifier for each member';

ALTER TABLE assessment ADD CONSTRAINT assessment_pk PRIMARY KEY ( assess_date,
                                                                  member_no );

CREATE TABLE centre (
    centre_id        NUMBER(7) NOT NULL,
    centre_name      VARCHAR2(20) NOT NULL,
    centre_street    VARCHAR2(20) NOT NULL,
    centre_town      VARCHAR2(20) NOT NULL,
    centre_postcode  VARCHAR2(8) NOT NULL,
    centre_phone     VARCHAR2(12) NOT NULL,
    staff_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN centre.centre_id IS
    'unique identifier for each centre';

COMMENT ON COLUMN centre.centre_name IS
    'the name of the centre';

COMMENT ON COLUMN centre.centre_street IS
    'the street number/name where the centre is located';

COMMENT ON COLUMN centre.centre_town IS
    'the town name in which the centre is located';

COMMENT ON COLUMN centre.centre_postcode IS
    'the postcode of the area where the centre is located';

COMMENT ON COLUMN centre.centre_phone IS
    'the phone number of the centre';

COMMENT ON COLUMN centre.staff_id IS
    'unique identifier for each staff member';

CREATE UNIQUE INDEX centre__idx ON
    centre (
        staff_id
    ASC );

ALTER TABLE centre ADD CONSTRAINT centre_pk PRIMARY KEY ( centre_id );

CREATE TABLE centre_class (
    class_number          NUMBER(7) NOT NULL,
    class_desc            VARCHAR2(50) NOT NULL,
    class_start_datetime  DATE NOT NULL,
    class_capacity        NUMBER(3) NOT NULL,
    class_cost            NUMBER(6, 2) NOT NULL,
    class_no_sess         NUMBER(5) NOT NULL,
    class_gender          CHAR(1) NOT NULL,
    facility_room_no      NUMBER(7) NOT NULL,
    centre_id             NUMBER(7) NOT NULL,
    class_duration        NUMBER(3, 2) NOT NULL,
    class_type_id         NUMBER(7) NOT NULL
);

ALTER TABLE centre_class
    ADD CHECK ( class_gender IN ( 'f', 'm', 'n' ) );

COMMENT ON COLUMN centre_class.class_number IS
    'the number of the class  which is unique within each centre';

COMMENT ON COLUMN centre_class.class_desc IS
    'the description of the class';

COMMENT ON COLUMN centre_class.class_start_datetime IS
    'the date and time of the start of the first session of the class';

COMMENT ON COLUMN centre_class.class_capacity IS
    'the capacity of the class indicating the number of staff+members it can accommodate';

COMMENT ON COLUMN centre_class.class_cost IS
    'the price of taking the class';

COMMENT ON COLUMN centre_class.class_no_sess IS
    'the number of sessions this class has';

COMMENT ON COLUMN centre_class.class_gender IS
    'the gender that this class is restricted to.
either n (not specified), m (male), f (female)';

COMMENT ON COLUMN centre_class.facility_room_no IS
    'the number of the facility which is unique within each centre.';

COMMENT ON COLUMN centre_class.centre_id IS
    'unique identifier for each centre';

COMMENT ON COLUMN centre_class.class_duration IS
    'the duration of the class represented to 2 decimal places';

COMMENT ON COLUMN centre_class.class_type_id IS
    'unique identifier for class type';

ALTER TABLE centre_class ADD CONSTRAINT class_pk PRIMARY KEY ( class_number,
                                                               centre_id );

CREATE TABLE centre_class_type (
    class_type     VARCHAR2(20) NOT NULL,
    class_type_id  NUMBER(7) NOT NULL
);

COMMENT ON COLUMN centre_class_type.class_type IS
    'the type of class.';

COMMENT ON COLUMN centre_class_type.class_type_id IS
    'unique identifier for class type';

ALTER TABLE centre_class_type ADD CONSTRAINT centre_class_type_pk PRIMARY KEY ( class_type_id );

CREATE TABLE class_session (
    session_date        DATE NOT NULL,
    session_attendance  CHAR(1) NOT NULL,
    class_number        NUMBER(7) NOT NULL,
    centre_id           NUMBER(7) NOT NULL,
    session_no          NUMBER(7) NOT NULL
);

COMMENT ON COLUMN class_session.session_date IS
    'the date at which the session takes place';

COMMENT ON COLUMN class_session.session_attendance IS
    'Attribute used to specify whether or not a member attended the class';

COMMENT ON COLUMN class_session.class_number IS
    'the number of the class  which is unique within each centre';

COMMENT ON COLUMN class_session.centre_id IS
    'unique identifier for each centre';

COMMENT ON COLUMN class_session.session_no IS
    'the session number used as a surrogate key';

ALTER TABLE class_session ADD CONSTRAINT session_pk PRIMARY KEY ( session_no );

ALTER TABLE class_session
    ADD CONSTRAINT class_session_nk UNIQUE ( centre_id,
                                             class_number,
                                             session_date );

CREATE TABLE class_staffing (
    class_staff_leader  CHAR(1) NOT NULL,
    staff_id            NUMBER(7) NOT NULL,
    class_number        NUMBER(7) NOT NULL,
    centre_id           NUMBER(7) NOT NULL
);

ALTER TABLE class_staffing
    ADD CHECK ( class_staff_leader IN ( 'n', 'y' ) );

COMMENT ON COLUMN class_staffing.class_staff_leader IS
    'Attribute specifies whether the staff is a class leader for the related class
either n (no) or y (yes)';

COMMENT ON COLUMN class_staffing.staff_id IS
    'unique identifier for each staff member';

COMMENT ON COLUMN class_staffing.class_number IS
    'the number of the class  which is unique within each centre';

COMMENT ON COLUMN class_staffing.centre_id IS
    'unique identifier for each centre';

ALTER TABLE class_staffing ADD CONSTRAINT class_staffing_pk PRIMARY KEY ( staff_id );

CREATE TABLE facility (
    facility_room_no   NUMBER(7) NOT NULL,
    facility_name      VARCHAR2(20) NOT NULL,
    facility_capacity  NUMBER(3) NOT NULL,
    facility_desc      VARCHAR2(50) NOT NULL,
    centre_id          NUMBER(7) NOT NULL
);

COMMENT ON COLUMN facility.facility_room_no IS
    'the number of the facility which is unique within each centre.';

COMMENT ON COLUMN facility.facility_name IS
    'the name of the facility';

COMMENT ON COLUMN facility.facility_capacity IS
    'the number of members+staff the facility can accommodate';

COMMENT ON COLUMN facility.facility_desc IS
    'the description of the facility';

COMMENT ON COLUMN facility.centre_id IS
    'unique identifier for each centre';

ALTER TABLE facility ADD CONSTRAINT facility_pk PRIMARY KEY ( facility_room_no,
                                                              centre_id );

CREATE TABLE member (
    member_no         NUMBER(7) NOT NULL,
    member_fname      VARCHAR2(20) NOT NULL,
    member_lname      VARCHAR2(20) NOT NULL,
    member_join_date  DATE NOT NULL,
    member_phone      VARCHAR2(12) NOT NULL,
    member_street     VARCHAR2(20) NOT NULL,
    member_town       VARCHAR2(20) NOT NULL,
    member_postcode   VARCHAR2(8) NOT NULL,
    centre_id         NUMBER(7) NOT NULL,
    member_no1        NUMBER(7)
);

COMMENT ON COLUMN member.member_no IS
    'unique identifier for each member';

COMMENT ON COLUMN member.member_fname IS
    'member''s first name';

COMMENT ON COLUMN member.member_lname IS
    'member''s last name';

COMMENT ON COLUMN member.member_join_date IS
    'the date on which the member joined';

COMMENT ON COLUMN member.member_phone IS
    'member''s phone number';

COMMENT ON COLUMN member.member_street IS
    'the street name/number where the member resides';

COMMENT ON COLUMN member.member_town IS
    'the town name of where the member resides';

COMMENT ON COLUMN member.member_postcode IS
    'postcode of the area where the member resides';

COMMENT ON COLUMN member.centre_id IS
    'unique identifier for each centre';

COMMENT ON COLUMN member.member_no1 IS
    'unique identifier for each member';

ALTER TABLE member ADD CONSTRAINT member_pk PRIMARY KEY ( member_no );

CREATE TABLE payment (
    payment_date          DATE NOT NULL,
    member_no             NUMBER(7) NOT NULL,
    payment_total_attend  NUMBER(3) NOT NULL,
    session_no            NUMBER(7) NOT NULL
);

COMMENT ON COLUMN payment.payment_date IS
    'the date on which the payment was made';

COMMENT ON COLUMN payment.member_no IS
    'unique identifier for each member';

COMMENT ON COLUMN payment.payment_total_attend IS
    'The total attendance of the member for the class';

COMMENT ON COLUMN payment.session_no IS
    'the session number used as a surrogate key';

ALTER TABLE payment
    ADD CONSTRAINT payment_pk PRIMARY KEY ( member_no,
                                            payment_date,
                                            session_no );

CREATE TABLE staff (
    staff_id                   NUMBER(7) NOT NULL,
    staff_fname                VARCHAR2(20) NOT NULL,
    staff_lname                VARCHAR2(20) NOT NULL,
    staff_phone                VARCHAR2(12) NOT NULL,
    staff_start_date           DATE NOT NULL,
    staff_role                 CHAR(1) NOT NULL,
    centre_id                  NUMBER(7) NOT NULL,
    staff_first_aid_certified  CHAR(1) NOT NULL
);

ALTER TABLE staff
    ADD CHECK ( staff_role IN ( 'A', 'C', 'D', 'M', 'P',
                                'S', 'T' ) );

ALTER TABLE staff
    ADD CHECK ( staff_first_aid_certified IN ( 'n', 'y' ) );

COMMENT ON COLUMN staff.staff_id IS
    'unique identifier for each staff member';

COMMENT ON COLUMN staff.staff_fname IS
    'staff member''s first name';

COMMENT ON COLUMN staff.staff_lname IS
    'staff_member''s last name';

COMMENT ON COLUMN staff.staff_phone IS
    'the staff member''s phone number';

COMMENT ON COLUMN staff.staff_start_date IS
    'the date on which the staff member started working';

COMMENT ON COLUMN staff.staff_role IS
    'the role of the staff member';

COMMENT ON COLUMN staff.centre_id IS
    'unique identifier for each centre';

COMMENT ON COLUMN staff.staff_first_aid_certified IS
    'attribute thats specifies whether the staff member is first aid certified
either y (yes, certified) or n (no, not certified)';

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

ALTER TABLE facility
    ADD CONSTRAINT centre_facility FOREIGN KEY ( centre_id )
        REFERENCES centre ( centre_id );

ALTER TABLE member
    ADD CONSTRAINT centre_member FOREIGN KEY ( centre_id )
        REFERENCES centre ( centre_id );

ALTER TABLE staff
    ADD CONSTRAINT centre_staff FOREIGN KEY ( centre_id )
        REFERENCES centre ( centre_id );

ALTER TABLE centre_class
    ADD CONSTRAINT facility_class FOREIGN KEY ( facility_room_no,
                                                centre_id )
        REFERENCES facility ( facility_room_no,
                              centre_id );

ALTER TABLE assessment
    ADD CONSTRAINT member_assignment FOREIGN KEY ( member_no )
        REFERENCES member ( member_no );

ALTER TABLE payment
    ADD CONSTRAINT member_payment FOREIGN KEY ( member_no )
        REFERENCES member ( member_no );

ALTER TABLE member
    ADD CONSTRAINT refers FOREIGN KEY ( member_no1 )
        REFERENCES member ( member_no );

ALTER TABLE class_session
    ADD CONSTRAINT relation_13 FOREIGN KEY ( class_number,
                                             centre_id )
        REFERENCES centre_class ( class_number,
                                  centre_id );

ALTER TABLE class_staffing
    ADD CONSTRAINT relation_14 FOREIGN KEY ( class_number,
                                             centre_id )
        REFERENCES centre_class ( class_number,
                                  centre_id );

ALTER TABLE payment
    ADD CONSTRAINT relation_15 FOREIGN KEY ( session_no )
        REFERENCES class_session ( session_no );

ALTER TABLE centre_class
    ADD CONSTRAINT relation_18 FOREIGN KEY ( class_type_id )
        REFERENCES centre_class_type ( class_type_id );

ALTER TABLE assessment
    ADD CONSTRAINT staff_assignment FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE centre
    ADD CONSTRAINT staff_centre_manager FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

ALTER TABLE class_staffing
    ADD CONSTRAINT staff_class_staffing FOREIGN KEY ( staff_id )
        REFERENCES staff ( staff_id );

spool off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             1
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
